#!/usr/bin/env bash
# gen-spec.sh — Generate servers.yaml from 1Password server.* items in Lab vault
#
# Queries all items named "server.*" in the Lab vault. For each item, reads:
#   env         — required field; "dev" or "prod"
#   hostname    — optional field; SSH target; defaults to server name
#   app.{name}  — one section per app (e.g. section "app.n8n"); section
#                 existence signals "deploy this app". Fields within the section
#                 prefixed env.* are reserved for host-specific env overrides
#                 (future: merged into .env by gen-env.sh)
#
# Output goes to stdout by default. Use --output to write to a file.
#
# Prerequisites on the admin workstation:
#   - op  (1Password CLI, authenticated)
#   - yq  (brew install yq)
#
# Usage:
#   ./gen-spec.sh [--output <file>]
#
# Examples:
#   ./gen-spec.sh                        # emit to stdout
#   ./gen-spec.sh --output servers.yaml  # write to file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common/lib.sh"

# ── Argument Parsing ──────────────────────────────────────────────────────────

usage() {
  echo "Usage: $0 [--output <file>]"
  exit 1
}

OUTPUT_FILE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    --help|-h) usage ;;
    *) usage ;;
  esac
done

# ── Preflight ─────────────────────────────────────────────────────────────────

command -v op  &>/dev/null || die "1Password CLI (op) not found. Install with: brew install --cask 1password-cli"
command -v jq  &>/dev/null || die "jq not found. Install with: brew install jq"

# ── Generate ──────────────────────────────────────────────────────────────────

log "Fetching server.* items from Lab vault..."

server_items=$(op item list --vault "$LAB_VAULT" --format json \
  | jq -r '.[] | select(.title | startswith("server.")) | .title')

if [[ -z "$server_items" ]]; then
  die "No server.* items found in vault '$LAB_VAULT'."
fi

yaml_lines=()
yaml_lines+=("# Generated by: $(basename "$0")")
yaml_lines+=("# Source of truth: 1Password Lab vault (server.* items)")
yaml_lines+=("# Re-run gen-spec.sh to refresh from 1Password.")
yaml_lines+=("")
yaml_lines+=("hosts:")

while IFS= read -r title; do
  [[ -z "$title" ]] && continue

  server_name="${title#server.}"
  log "  Fetching $title..."

  item_json=$(op item get "$title" --vault "$LAB_VAULT" --format json)

  # Required fields
  env_val=$(echo "$item_json" | jq -r '.fields[] | select(.label == "env") | .value' || true)
  [[ -z "$env_val" ]] && die "Item '$title' is missing required field 'env'."

  # Optional fields
  hostname_val=$(echo "$item_json" | jq -r '.fields[] | select(.label == "hostname") | .value' || true)

  # App list: all sections with label prefix "app."
  app_names=$(echo "$item_json" \
    | jq -r '.sections[]? | select(.label != null and (.label | startswith("app."))) | .label | ltrimstr("app.")' \
    || true)

  [[ -z "$app_names" ]] && die "Item '$title' has no app.* sections — at least one required."

  yaml_lines+=("  - server: $server_name")
  yaml_lines+=("    env: $env_val")
  [[ -n "$hostname_val" ]] && yaml_lines+=("    hostname: $hostname_val")
  yaml_lines+=("    services:")

  while IFS= read -r app; do
    [[ -z "$app" ]] && continue
    yaml_lines+=("      - $app")
  done <<< "$app_names"

done <<< "$server_items"

# ── Emit ──────────────────────────────────────────────────────────────────────

if [[ -n "$OUTPUT_FILE" ]]; then
  printf '%s\n' "${yaml_lines[@]}" > "$OUTPUT_FILE"
  log "Spec written to $OUTPUT_FILE"
else
  printf '%s\n' "${yaml_lines[@]}"
fi
